17 이미지 업로드 구현
h-jjang/bauction pull request #41
Opened 2022-04-30 06:43 UTC by 0BVer

### 작업 내용

- S3 이미지 업로드 구현

### 주의사항

- aws 관련 application.yml 파일이 없으면 오류가 날 수 있습니다 (슬랙에 공유하겠습니다)
   - application-aws.yml
   - application-credential.yml

2022-04-30 07:11 UTC, 0BVer reviewed
더 필요한거 있는지 확인 부탁드립니다

2022-04-30 09:30 UTC, Yunkeun requested changes
오타 수정해주시고, 메서드 중복 부분 확인하셔서 더 좋은 방법으로 수정 혹은 유지해서 머지하면 좋을 것 같습니다!!

2022-04-30 09:30 UTC, Yunkeun commented on backend/src/main/java/com/hjjang/backend/domain/image/controller/ImageController.java
> +    public ResponseEntity<HttpStatus> deleteIMage(@PathVariable Long imageId) {
```suggestion
    public ResponseEntity<HttpStatus> deleteImage(@PathVariable Long imageId) {
```

오타있네요!

2022-04-30 09:30 UTC, Yunkeun commented on backend/src/main/java/com/hjjang/backend/infra/uploader/component/S3Uploader.java
> +    }
LocalUploader랑 메서드 중복이 발생하네요
이런 경우 중복 방지하려면 어떤 방식을 쓰면 좋을까요??

제 생각엔 ImageUploader를 implements하는 Uploader 클래스를 생성해서 공통되는 메서드를 구현하고 해당 클래스를 extends해서 upload만 override해도 좋을 것 같다는 생각을 해봅니다!
다른 분들 의견 궁금합니다.

개인적으로 궁금한거라서 달아 놓습니다.

2022-04-30 09:30 UTC, Yunkeun commented on backend/src/main/java/com/hjjang/backend/infra/uploader/component/S3Uploader.java
> +    }
여기도 중복이네요!

2022-04-30 11:50 UTC, kim1387 commented on backend/src/main/java/com/hjjang/backend/infra/uploader/component/S3Uploader.java
> +    }
좋은 생각인것 같습니다!

2022-04-30 11:52 UTC, kim1387 commented on backend/build.gradle
> +    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
어느 것이 더 좋은지는 잘 모르겠지만 버전을 직접 명시하기 보다 spring boot에서 적절한 버전을 찾도록 두는건 어떨까요??

2022-04-30 12:07 UTC, kim1387 commented
현재 infra 패키지 안에 aws와 관련 없는 이미지 업로드 패키지들이 들어가 있는 것 같습니다! 한번 확인 부탁드립니다!
[package structure](https://www.notion.so/ce19f003/Package-Structure-95ae619238af409c97b99793e844520c)에 따르면 
- **infra는 외부와 관련된 서비스 파일을 관리한다.**
    - ex) AWS S3 관련 service
라고 나와있는데 local uploader와 관련된 것은 domain 하위 패키지 안에 있는 것이 맞는 구조가 아닌가 생각이 듭니다!
[참고](https://github.com/Instagram-Clone-Coding/Spring_instagram-clone/tree/develop/src/main/java/cloneproject/Instagram/infra)

2022-04-30 12:07 UTC, kim1387 commented
그리고 compoent 패키지 안에 있는 클래스들은 service class로 봐도 괜찮을 것 같은데 component로 만드신 이유가 있을까요??

2022-04-30 12:59 UTC, 0BVer commented on backend/src/main/java/com/hjjang/backend/infra/uploader/component/S3Uploader.java
> +    }
해당 부분 반영 해보겠습니다!

2022-04-30 12:59 UTC, 0BVer commented on backend/src/main/java/com/hjjang/backend/infra/uploader/component/S3Uploader.java
> +    }
확인했습니다!

2022-04-30 13:01 UTC, 0BVer commented on backend/build.gradle
> +    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
버전 제외한 상태로 테스트 해보고 반영해보겠습니다

2022-04-30 13:17 UTC, 0BVer commented
해당 클래스를 서비스 클래스로 봐야 할까요? 아직 컴포넌트와 서비스의 차이를 잘 모르겠습니다...

2022-04-30 13:20 UTC, 0BVer commented on backend/build.gradle
> +    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
테스트 해보니 `implementation 'org.springframework.cloud:spring-cloud-starter-aws'`로 하였을 때 빌드 오류가 생기는것 같습니다. 테스트 해볼만한 다른 표기법이 있을까요?

2022-04-30 13:48 UTC, 0BVer commented
PR 이슈 반영하여 이미지 업로더 코드 중복 해결, 컴포넌트에서 서비스로 변경, 로컬 업로더 이미지 도메인으로 이동해서 다시 풀리퀘 오픈했습니다. 확인 부탁드립니다.

2022-04-30 13:49 UTC, 0BVer commented on backend/src/main/java/com/hjjang/backend/domain/image/controller/ImageController.java
> +    public ResponseEntity<HttpStatus> deleteIMage(@PathVariable Long imageId) {
확인해서 반영했습니다

2022-04-30 15:52 UTC, Yunkeun approved these changes
확인했습니다~!

2022-05-02 05:16 UTC, kim1387 commented
@0BVer 확인이 늦었네요.. ㅠㅠ @controller, @service, @repository등등 모두 사실 component이기 때문에

@Controller
![image](https://user-images.githubusercontent.com/58874807/166187394-a3eadbaf-5f05-4589-9e20-10dc128a2c58.png)

@Service
![image](https://user-images.githubusercontent.com/58874807/166187435-506a5d78-853c-48b0-ba39-46a18c6fc41c.png)

다만 역할을 명시하기 위해 service의 역할을 수행한다면 service로 분리하는게 맞지 않을까 생각해서 말씀드렸습니다!

2022-05-02 10:57 UTC, 0BVer reviewed
확인 완료했습니다

2022-05-03 14:56 UTC, merged